"""Run remediations from a CloudShield JSON results file.

Two deliberate differences from the original implementation:

* Actions are boto3 calls, not shell commands. The results file is untrusted
  input -- interpolating resource names from it into a ``shell=True`` command
  string was arbitrary code execution for anyone who could write that file.
* The session comes from ``core.auth``, the same place ``main.py`` gets it, so
  ``--fix`` acts on the account that was scanned rather than on whatever
  credentials the AWS CLI happens to pick up.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Sequence

from botocore.exceptions import BotoCoreError, ClientError
from dotenv import load_dotenv

from core.auth import AWSAuthManager
from core.models import CheckResult
from remediators import registry

EXIT_OK = 0
EXIT_FAILED_ACTIONS = 1
EXIT_ERROR = 2


def load_checks(path: Path) -> List[CheckResult]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)

    raw_checks = payload.get("checks")
    if not isinstance(raw_checks, list):
        raise ValueError("Invalid results format: 'checks' must be a list.")

    checks: List[CheckResult] = []
    for entry in raw_checks:
        if not isinstance(entry, dict):
            continue
        checks.append(
            CheckResult(
                service=str(entry.get("service", "unknown")),
                resource_id=str(entry.get("resource_id", "")),
                resource_type=str(entry.get("resource_type", "unknown")),
                check_id=str(entry.get("check_id", "")),
                check_name=str(entry.get("check_name", "")),
                status=str(entry.get("status", "")).upper(),
                severity=str(entry.get("severity", "Low")),
                cis_control=str(entry.get("cis_control", "N/A")),
                message=str(entry.get("message", "")),
                details=entry.get("details") or {},
                region=str(entry.get("region", "global")),
                suppressed=bool(entry.get("suppressed", False)),
                suppression_reason=str(entry.get("suppression_reason", "")),
            )
        )
    return checks


def print_plan(results: Sequence[registry.RemediationResult]) -> None:
    if not results:
        print("No automated remediations are available for the failed checks in this file.")
        return

    for result in results:
        marker = " [DESTRUCTIVE]" if result.destructive else ""
        print("-")
        print(f"Check:    {result.check_id}{marker}")
        print(f"Resource: {result.resource_id} ({result.region})")
        print(f"Status:   {result.status}")
        print(f"Action:   {result.message}")
        if result.command:
            print(f"CLI equivalent: {result.command}")


def summarise(results: Sequence[registry.RemediationResult]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for result in results:
        counts[result.status] = counts.get(result.status, 0) + 1
    return counts


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="cloudshield-remediate",
        description="Plan or apply remediations from a CloudShield results file.",
    )
    parser.add_argument(
        "--results",
        default="cloudshield_results.json",
        help="Path to JSON results generated by main.py.",
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help="Apply the allowed remediations. Without this, actions are only listed.",
    )
    parser.add_argument(
        "--allow",
        nargs="+",
        default=[],
        metavar="CHECK_ID",
        help="Check ids --fix is permitted to act on, or 'all'. Required for --fix.",
    )
    parser.add_argument(
        "--list-checks",
        action="store_true",
        help="List every check id with an automated remediation, then exit.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    load_dotenv()
    args = build_parser().parse_args(argv)

    if args.list_checks:
        print("Check ids with an automated remediation:\n")
        for check_id, remediation in sorted(registry.REMEDIATIONS.items()):
            if not remediation.automated:
                continue
            flag = " [destructive]" if remediation.destructive else ""
            print(f"  {check_id}{flag}\n      {remediation.description}")
        return EXIT_OK

    results_path = Path(args.results)
    if not results_path.exists():
        print(
            f"Results file not found: {results_path}. Run main.py first to generate it.",
            file=sys.stderr,
        )
        return EXIT_ERROR

    try:
        checks = load_checks(results_path)
    except (ValueError, json.JSONDecodeError) as exc:
        print(f"Could not read {results_path}: {exc}", file=sys.stderr)
        return EXIT_ERROR

    if args.fix and not args.allow:
        print(
            "--fix requires --allow with one or more check ids (or 'all').\n"
            "Run with --list-checks to see what can be automated.",
            file=sys.stderr,
        )
        return EXIT_ERROR

    session = None
    if args.fix:
        try:
            session = AWSAuthManager().get_session()
        except (RuntimeError, BotoCoreError, ClientError) as exc:
            print(f"AWS authentication failed: {exc}", file=sys.stderr)
            return EXIT_ERROR

        identity = "unknown account"
        try:
            identity = session.client("sts").get_caller_identity().get("Account", "unknown")
        except (BotoCoreError, ClientError):
            pass
        print(f"Applying remediations to account {identity}.\n")

    results = registry.run(
        session, checks, allow=args.allow, apply_changes=args.fix  # type: ignore[arg-type]
    )
    print_plan(results)

    counts = summarise(results)
    if counts:
        print("\n" + " | ".join(f"{status}: {count}" for status, count in sorted(counts.items())))

    return EXIT_FAILED_ACTIONS if counts.get(registry.STATUS_FAILED) else EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
