"""Run optional automated remediations from CloudShield JSON results."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Dict, List, Tuple


def load_results(path: Path) -> Dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def remediation_for_check(check: Dict) -> Tuple[str, str]:
    check_id = str(check.get("check_id", ""))
    details = check.get("details", {}) or {}
    resource_id = str(check.get("resource_id", ""))

    if check_id == "EC2-EBS-ENCRYPTION-BY-DEFAULT":
        return (
            "aws ec2 enable-ebs-encryption-by-default",
            "Enable account-level EBS encryption by default.",
        )

    if check_id == "EC2-IMDSV2-REQUIRED":
        instance_id = resource_id
        if instance_id:
            return (
                f"aws ec2 modify-instance-metadata-options --instance-id {instance_id} --http-tokens required",
                "Require IMDSv2 on the affected instance.",
            )

    if check_id == "S3-ACCOUNT-PUBLIC-ACCESS-BLOCK":
        account_id = resource_id.replace("account:", "")
        if account_id:
            return (
                "aws s3control put-public-access-block "
                f"--account-id {account_id} "
                "--public-access-block-configuration "
                "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true",
                "Enable all account-level S3 public access block controls.",
            )

    if check_id == "S3-PUBLIC-ACCESS-BLOCK":
        bucket = details.get("bucket") or resource_id
        if bucket:
            return (
                "aws s3api put-public-access-block "
                f"--bucket {bucket} "
                "--public-access-block-configuration "
                "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true",
                "Enable all bucket-level S3 public access block controls.",
            )

    if check_id == "IAM-USER-KEY-AGE":
        user_name = details.get("user")
        access_key_id = details.get("access_key_id")
        if user_name and access_key_id:
            return (
                f"aws iam update-access-key --user-name {user_name} --access-key-id {access_key_id} --status Inactive",
                "Disable stale IAM access key before rotation.",
            )

    return ("", "No automated command mapped for this failed check.")


def collect_actions(checks: List[Dict]) -> List[Tuple[Dict, str, str]]:
    actions: List[Tuple[Dict, str, str]] = []
    for check in checks:
        if str(check.get("status", "")).upper() != "FAIL":
            continue
        command, description = remediation_for_check(check)
        if command:
            actions.append((check, command, description))
    return actions


def run_actions(actions: List[Tuple[Dict, str, str]], execute: bool) -> None:
    if not actions:
        print("No auto-remediation actions available for current failed checks.")
        return

    for check, command, description in actions:
        print("-")
        print(f"Check: {check.get('check_id', 'unknown')} | Resource: {check.get('resource_id', 'unknown')}")
        print(f"Action: {description}")
        print(f"Command: {command}")
        if not execute:
            continue

        try:
            result = subprocess.run(command, shell=True, check=False, text=True, capture_output=True)
        except OSError as exc:
            print(f"Execution failed: {exc}")
            continue

        print(f"Exit code: {result.returncode}")
        if result.stdout.strip():
            print(result.stdout.strip())
        if result.stderr.strip():
            print(result.stderr.strip())


def main() -> None:
    parser = argparse.ArgumentParser(description="CloudShield remediation runner")
    parser.add_argument(
        "--results",
        default="cloudshield_results.json",
        help="Path to JSON results generated by main.py",
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help="Execute remediation commands. Without this flag, commands are only listed.",
    )
    args = parser.parse_args()

    results_path = Path(args.results)
    if not results_path.exists():
        raise FileNotFoundError(
            f"Results file not found: {results_path}. Run main.py first to generate cloudshield_results.json."
        )

    results = load_results(results_path)
    checks = results.get("checks", [])
    if not isinstance(checks, list):
        raise ValueError("Invalid results format: 'checks' must be a list.")

    actions = collect_actions(checks)
    run_actions(actions, execute=args.fix)


if __name__ == "__main__":
    main()
